### ISSUE TITLE
`make_output_dir': uninitialized constant #<Class:Ever2boost::Util>::FileUtils (NameError)

### ISSUE THREAD

**Issue by thejasonparker** [BoostIO/ever2boost#10]
Running the` ever2boost convert` command on macOS High Sierra v10.13.2 (17C88) generates the following error.

```
/Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/util.rb:5:in `make_output_dir': uninitialized constant #<Class:Ever2boost::Util>::FileUtils (NameError)
	from /Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/util.rb:9:in `make_notes_dir'
	from /Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/json_generator.rb:21:in `output'
	from /Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/enex_converter.rb:11:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/cli.rb:26:in `convert'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/exe/ever2boost:4:in `<top (required)>'
	from /usr/local/bin/ever2boost:22:in `load'
	from /usr/local/bin/ever2boost:22:in `<main>'
```

**Comment by AlexWootton** [comment]
I see similar when running under macOS 10.12.6 (16G1114)

```ever2boost convert ~/Downloads/personal.enex
converting...
/Library/Ruby/Gems/2.0.0/gems/ever2boost-0.1.5/lib/ever2boost/util.rb:5:in `make_output_dir': uninitialized constant Class::FileUtils (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/ever2boost-0.1.5/lib/ever2boost/util.rb:9:in `make_notes_dir'
	from /Library/Ruby/Gems/2.0.0/gems/ever2boost-0.1.5/lib/ever2boost/json_generator.rb:21:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/ever2boost-0.1.5/lib/ever2boost/enex_converter.rb:11:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/ever2boost-0.1.5/lib/ever2boost/cli.rb:26:in `convert'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/ever2boost-0.1.5/exe/ever2boost:4:in `<top (required)>'
	from /usr/local/bin/ever2boost:23:in `load'
	from /usr/local/bin/ever2boost:23:in `<main>'
```

Any assistance would be greatly appreciated.

**Comment by jdossgollin** [comment]
Same issue here

```
processing...
/Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/evernote_authorizer.rb:58:in `import': uninitialized constant Ever2boost::EvernoteAuthorizer::FileUtils (NameError)
Did you mean?  FileTest
	from /Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/cli.rb:16:in `import'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/ever2boost-0.1.5/exe/ever2boost:4:in `<top (required)>'
	from /usr/local/bin/ever2boost:22:in `load'
	from /usr/local/bin/ever2boost:22:in `<main>'
```

**Comment by feigi** [comment]
Can we get a fix for this issue, or is this project dead?
