### ISSUE TITLE
uninitialized constant Ever2boost::EvernoteAuthorizer::FileUtils (NameError)

### ISSUE THREAD

**Issue by arguser** [BoostIO/ever2boost#7]
Issue while trying to import on Ubuntu, fixed by adding `require 'fileutils'` on `evernote_authorizer.rb`
```
/var/lib/gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/evernote_authorizer.rb:58:in `import': uninitialized constant Ever2boost::EvernoteAuthorizer::FileUtils (NameError)
Did you mean?  FileTest
	from /var/lib/gems/2.3.0/gems/ever2boost-0.1.5/lib/ever2boost/cli.rb:16:in `import'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /var/lib/gems/2.3.0/gems/ever2boost-0.1.5/exe/ever2boost:4:in `<top (required)>'
	from /usr/local/bin/ever2boost:22:in `load'
	from /usr/local/bin/ever2boost:22:in `<main>'

```

**Comment by narukami894** [comment]
this error will be resolved by https://github.com/BoostIO/ever2boost/pull/11
